version: '2'
services:
  mysql:
    container_name: mysql
    restart: always
    image: mysql:5.7
    ports:
      - "3606:3306"
    volumes:
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=root
    networks:
      - custom
  www:
    image: itc-php-7.2:latest
    restart: always
    container_name: www
    expose:
       - "80"
    volumes:
       - ./docroot/www:/var/www/html
       - ./vhost/:/etc/apache2/sites-enabled/
    environment:
      - VIRTUAL_HOST=somarpon.com,www.somarpon.com 
    depends_on:
      - mysql
    networks:
      - custom
networks:
  custom:
    external: true
