version: "3.1"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      #- ./data/conf/custom_settings.conf:/etc/nginx/conf.d/custom_settings.conf:ro
      - ./data/conf/:/etc/nginx/conf.d/
      #- ./data/conf.d:/etc/nginx/conf.d
      - ./data/certs:/etc/nginx/certs
      #- ./data/vhost.d:/etc/nginx/vhost.d
      #- ./data/logs:/etc/nginx/logs
    environment:
      - HTTPS_METHOD=nohttp
      - DEFAULT_HOST=certbot.mock.com
    networks:
      - laravel
networks:
  laravel:
    external: true

